sudo: required

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

language: java

jdk:
  - oraclejdk8

#DEFOLD_AUTH=auth token
env:
  global:
    - secure: "Uu3qUk7xk1i830NEuvVcRFI3IuVXetkV8QxY9cOrLEqvpKuGhn0q0Wai/es+iB/OyIlSyWAb5jtpCyhMPG55/OXDeq6/1bigQU0WqJ+yCugHd0CXNRaSIJWhd665YERVaYYI/wPvNp0QSqLeGrpn7G4zYXX1W0oDylNQXp2FMR2GoBkzLrbVhZc/mx1XaEYQIdOXCIOcjrV+gRgqRMEPuNKl47In+4LQuPbWokhePfWEJX7GF7nFAvnqZXYBSjZb4IbNA/cOaIjfaUx1wu7Vl8D+SSCxfhqpl5mFJyTBIEWHZqdJYZa6EIbcuKuC4m8XnqLkN4IqWKj4Eopbh28x6QkbIpumybxlgBlGMjugTsEBVm+ofqrICsGoLD2ShMUD/h2NCBdesl00My60sCLu6UmnRArzCLGlx+lUdsp7+03+P9BCL1q9nrv645DmZ0LbDsGLO18UhYeWc58NVHph7mVfUoi7FWP3gZe6zas/RqhfxbZJ9aQ1SoOmZYi9W1hhpc+OIPk5qw73/92orxoDhrECh7SgXHLNk5Oo5InyH5ZQbF9lOE6IKKmYUoqcALVGzwtg1TU1OfvwUKgDG+iWEw0Uf8e3MDU6lrEN/aGDZgeyfEBmeNvceo3f02K+zLX5ByqA4hn7/L5Cmq3adesR3JKaARaQQ9k/DkgWpOUEcpc="
    - DEFOLD_USER=bjorn.ritzl@king.com

script:
  - "./.test/run.sh"
