sudo: required
script:
- "./.test/run.sh"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
language: java
jdk:
- oraclejdk11
env:
  global:
  - DEFOLD_AUTH=foobar
  - DEFOLD_USER=bjorn.ritzl@gmail.com
  - DEFOLD_BOOSTRAP_COLLECTION=/test/test.collectionc
